services:
  mysql:
    container_name: mysql
    image: mysql:8.0-oracle
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_AUTH_PLUGIN: $MYSQL_AUTH_PLUGIN
    volumes:
      - mysql_db:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    depends_on:
      - mysql
    container_name: wordpress
    image: wordpress:6.2.0-fpm-alpine
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: $MYSQL_USER
      WORDPRESS_DB_PASSWORD: $MYSQL_PASSWORD
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    volumes:
      - html:/var/www/html
    networks:
      - wordpress_network

volumes:
  html:
  mysql_db:

networks:
  wordpress_network:
    name: wordpress_network
    driver: bridge
